import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIRouterProvider } from "./providers/NextUIRouterProvider";
import MainHeader from "./components/MainHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIRouterProvider>
          <MainHeader />
          {children}
        </NextUIRouterProvider>
      </body>
    </html>
  );
}
